sudo: required
services:
  - docker

before_install:
  - docker build -t jaderpereiralima/docker-react -f Dockerfile.dev .

script:
  - docker run jaderpereiralima/docker-react npm run test -- --coverage